version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - DOMAIN=${DOMAIN}
    restart: always
